version: "3.9"  # optional since v1.27.0
services:
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kyle-board
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  server:
    ports:
      - "8080"
    depends_on:
      - db
      - redis
    environment:
      PROD_DB_HOST: db
      PROD_REDIS_HOST: redis
      PROD_PORT: 8080
    build:
      context: .
      dockerfile: Dockerfile
    