import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/Layout";
import { withApollo } from "../utils/withApollo";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>asdf</Layout>
        </>
    );
};

export default withApollo({ ssr: true })(Home);
